[[questions]]
question = "Which year did the first human-made object, Sputnik 1, launch into space?"
choices = [
  "1957",
  "1961",
  "1969",
  "1975"
]
# Answer: Choice 1 (1957)

[[questions]]
question = "Who was the first American to orbit the Earth?"
choices = [
  "Alan Shepard",
  "Neil Armstrong",
  "John Glenn",
  "Buzz Aldrin"
]
# Answer: Choice 3 (John Glenn)

[[questions]]
question = "Which mission was the first to land humans on the Moon?"
choices = [
  "Apollo 8",
  "Apollo 11",
  "Apollo 13",
  "Apollo 17"
]
# Answer: Choice 2 (Apollo 11)

[[questions]]
question = "What was the name of the first space shuttle orbiter?"
choices = [
  "Discovery",
  "Columbia",
  "Challenger",
  "Endeavour"
]
# Answer: Choice 2 (Columbia)

[[questions]]
question = "Which space probe provided the first close-up images of Mars?"
choices = [
  "Voyager 1",
  "Cassini",
  "Mars Pathfinder",
  "Mariner 4"
]
# Answer: Choice 4 (Mariner 4)

[[questions]]
question = "Who was the first woman to travel to space?"
choices = [
  "Valentina Tereshkova",
  "Sally Ride",
  "Yuri Gagarin",
  "Mae Jemison"
]
# Answer: Choice 1 (Valentina Tereshkova)

[[questions]]
question = "Which space mission experienced a major oxygen tank explosion but safely returned to Earth?"
choices = [
  "Apollo 11",
  "Apollo 13",
  "Apollo 17",
  "Apollo 10"
]
# Answer: Choice 2 (Apollo 13)

[[questions]]
question = "What was the name of the first space station launched by the Soviet Union?"
choices = [
  "Skylab",
  "Mir",
  "Salyut 1",
  "International Space Station (ISS)"
]
# Answer: Choice 3 (Salyut 1)

[[questions]]
question = "Who was the first person to perform a spacewalk?"
choices = [
  "Buzz Aldrin",
  "Neil Armstrong",
  "Yuri Gagarin",
  "Alexei Leonov"
]
# Answer: Choice 4 (Alexei Leonov)

[[questions]]
question = "Which space telescope was launched in 1990 and has provided stunning images of the universe?"
choices = [
  "Hubble Space Telescope",
  "Spitzer Space Telescope",
  "Kepler Space Telescope",
  "Chandra X-ray Observatory"
]
# Answer: Choice 1 (Hubble Space Telescope)

[correct_answers]
correct_answers = [1, 3, 2, 2, 4, 1, 2, 3, 4, 1]
