[[questions]]
question = "Who is the founder of Marvel Studios?"
choices = [
  "Stan Lee",
  "Kevin Feige",
  "Robert Downey Jr.",
  "Chris Evans"
]
# Answer: Choice 2 (Kevin Feige)

[[questions]]
question = "Which actor portrays Iron Man in the Marvel Cinematic Universe?"
choices = [
  "Chris Hemsworth",
  "Tom Hiddleston",
  "Chris Pratt",
  "Robert Downey Jr."
]
# Answer: Choice 4 (Robert Downey Jr.)

[[questions]]
question = "Who is the director of the movie 'Avengers: Endgame'?"
choices = [
  "Joss Whedon",
  "James Gunn",
  "Anthony Russo",
  "Taika Waititi"
]
# Answer: Choice 3 (Anthony Russo)

[[questions]]
question = "What is the name of Thor's enchanted hammer?"
choices = [
  "Mjolnir",
  "Stormbreaker",
  "Gungnir",
  "Aegis"
]
# Answer: Choice 1 (Mjolnir)

[[questions]]
question = "Which Infinity Stone grants the power of time manipulation?"
choices = [
  "Space Stone",
  "Mind Stone",
  "Reality Stone",
  "Time Stone"
]
# Answer: Choice 4 (Time Stone)

[[questions]]
question = "Who is the main villain in the movie 'Black Panther'?"
choices = [
  "Thanos",
  "Loki",
  "Erik Killmonger",
  "Ultron"
]
# Answer: Choice 3 (Erik Killmonger)

[[questions]]
question = "Which character is known as the 'God of Mischief'?"
choices = [
  "Thor",
  "Iron Man",
  "Loki",
  "Hulk"
]
# Answer: Choice 3 (Loki)

[correct_answers]
correct_answers = [2, 4, 3, 1, 4, 3, 3]
