[[questions]]
question = "What is the largest planet in our solar system?"
choices = ["Jupiter", "Saturn", "Mars", "Earth"]

[[questions]]
question = "Who painted the Mona Lisa?"
choices = ["Pablo Picasso", "Vincent van Gogh", "Michelangelo", "Leonardo da Vinci"]

[[questions]]
question = "What is the chemical symbol for silver?"
choices = ["Au", "Ag", "Hg", "Pt"]

[correct_answers]
correct_answers = [1, 4, 2] 