FROM python:3.11-slim-buster

WORKDIR /app

# Copy the delete_directories.sh script to /app
COPY delete_directories.sh /app/

# Set execute permissions for the script
RUN chmod +x /app/delete_directories.sh

